/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AboutSection = IDL.Record({
  'bio' : IDL.Text,
  'profilePhoto' : IDL.Opt(ExternalBlob),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContactInfo = IDL.Record({
  'socialLinks' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'email' : IDL.Text,
});
export const MediaItem = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'blob' : ExternalBlob,
  'description' : IDL.Text,
  'mediaType' : IDL.Text,
  'category' : IDL.Text,
  'position' : IDL.Nat,
});
export const Category = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const SubGallery = IDL.Record({
  'id' : IDL.Text,
  'thumbnail' : ExternalBlob,
  'name' : IDL.Text,
  'position' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  '_resetAdminWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearFeaturedMediaItem' : IDL.Func([], [], []),
  'createCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createSubGallery' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, IDL.Nat],
      [],
      [],
    ),
  'deleteCategory' : IDL.Func([IDL.Text], [], []),
  'deleteMediaItem' : IDL.Func([IDL.Text], [], []),
  'deleteSubGallery' : IDL.Func([IDL.Text], [], []),
  'getAboutSection' : IDL.Func([], [IDL.Opt(AboutSection)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactInfo' : IDL.Func([], [IDL.Opt(ContactInfo)], ['query']),
  'getFeaturedMediaItem' : IDL.Func([], [IDL.Opt(MediaItem)], ['query']),
  'getMediaItem' : IDL.Func([IDL.Text], [IDL.Opt(MediaItem)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllMedia' : IDL.Func([], [IDL.Vec(MediaItem)], ['query']),
  'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'listMediaByCategory' : IDL.Func([IDL.Text], [IDL.Vec(MediaItem)], ['query']),
  'listSubGalleries' : IDL.Func([], [IDL.Vec(SubGallery)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setFeaturedMediaItem' : IDL.Func([IDL.Text], [], []),
  'updateAboutSection' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'updateContactInfo' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      [],
      [],
    ),
  'updateMediaItem' : IDL.Func([MediaItem], [], []),
  'updateSubGalleryName' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateSubGalleryThumbnail' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'uploadMediaItem' : IDL.Func([MediaItem], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AboutSection = IDL.Record({
    'bio' : IDL.Text,
    'profilePhoto' : IDL.Opt(ExternalBlob),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContactInfo = IDL.Record({
    'socialLinks' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'email' : IDL.Text,
  });
  const MediaItem = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'blob' : ExternalBlob,
    'description' : IDL.Text,
    'mediaType' : IDL.Text,
    'category' : IDL.Text,
    'position' : IDL.Nat,
  });
  const Category = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const SubGallery = IDL.Record({
    'id' : IDL.Text,
    'thumbnail' : ExternalBlob,
    'name' : IDL.Text,
    'position' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  '_resetAdminWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearFeaturedMediaItem' : IDL.Func([], [], []),
    'createCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createSubGallery' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, IDL.Nat],
        [],
        [],
      ),
    'deleteCategory' : IDL.Func([IDL.Text], [], []),
    'deleteMediaItem' : IDL.Func([IDL.Text], [], []),
    'deleteSubGallery' : IDL.Func([IDL.Text], [], []),
    'getAboutSection' : IDL.Func([], [IDL.Opt(AboutSection)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactInfo' : IDL.Func([], [IDL.Opt(ContactInfo)], ['query']),
    'getFeaturedMediaItem' : IDL.Func([], [IDL.Opt(MediaItem)], ['query']),
    'getMediaItem' : IDL.Func([IDL.Text], [IDL.Opt(MediaItem)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllMedia' : IDL.Func([], [IDL.Vec(MediaItem)], ['query']),
    'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'listMediaByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MediaItem)],
        ['query'],
      ),
    'listSubGalleries' : IDL.Func([], [IDL.Vec(SubGallery)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setFeaturedMediaItem' : IDL.Func([IDL.Text], [], []),
    'updateAboutSection' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [], []),
    'updateContactInfo' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        [],
        [],
      ),
    'updateMediaItem' : IDL.Func([MediaItem], [], []),
    'updateSubGalleryName' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateSubGalleryThumbnail' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'uploadMediaItem' : IDL.Func([MediaItem], [], []),
  });
};

export const init = ({ IDL }) => { return []; };