/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutSection {
  'bio' : string,
  'profilePhoto' : [] | [ExternalBlob],
}
export interface Category { 'id' : string, 'name' : string }
export interface ContactInfo {
  'socialLinks' : Array<[string, string]>,
  'email' : string,
}
export type ExternalBlob = Uint8Array;
export interface MediaItem {
  'id' : string,
  'title' : string,
  'blob' : ExternalBlob,
  'description' : string,
  'mediaType' : string,
  'category' : string,
  'position' : bigint,
}
export interface SubGallery {
  'id' : string,
  'thumbnail' : ExternalBlob,
  'name' : string,
  'position' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  '_resetAdminWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearFeaturedMediaItem' : ActorMethod<[], undefined>,
  'createCategory' : ActorMethod<[string, string], undefined>,
  'createSubGallery' : ActorMethod<
    [string, string, ExternalBlob, bigint],
    undefined
  >,
  'deleteCategory' : ActorMethod<[string], undefined>,
  'deleteMediaItem' : ActorMethod<[string], undefined>,
  'deleteSubGallery' : ActorMethod<[string], undefined>,
  'getAboutSection' : ActorMethod<[], [] | [AboutSection]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInfo' : ActorMethod<[], [] | [ContactInfo]>,
  'getFeaturedMediaItem' : ActorMethod<[], [] | [MediaItem]>,
  'getMediaItem' : ActorMethod<[string], [] | [MediaItem]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllMedia' : ActorMethod<[], Array<MediaItem>>,
  'listCategories' : ActorMethod<[], Array<Category>>,
  'listMediaByCategory' : ActorMethod<[string], Array<MediaItem>>,
  'listSubGalleries' : ActorMethod<[], Array<SubGallery>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setFeaturedMediaItem' : ActorMethod<[string], undefined>,
  'updateAboutSection' : ActorMethod<[string, [] | [ExternalBlob]], undefined>,
  'updateContactInfo' : ActorMethod<
    [string, Array<[string, string]>],
    undefined
  >,
  'updateMediaItem' : ActorMethod<[MediaItem], undefined>,
  'updateSubGalleryName' : ActorMethod<[string, string], undefined>,
  'updateSubGalleryThumbnail' : ActorMethod<[string, ExternalBlob], undefined>,
  'uploadMediaItem' : ActorMethod<[MediaItem], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];